# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Walkmore' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Walkmore
pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'FBSDKLoginKit'
    pod 'SnapKit', '0.30.0.beta2'
    pod 'Mapbox-iOS-SDK', '~> 3.3.3'
    pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :tag => 'v0.6.0'
    pod 'MapboxGeocoder.swift', :git => 'https://github.com/mapbox/MapboxGeocoder.swift.git', :tag => 'v0.5.0'
    pod 'MapboxStatic.swift', :git => 'https://github.com/mapbox/MapboxStatic.swift.git', :tag => 'v0.6.0'
    pod 'ReachabilitySwift'
pod 'TGLParallaxCarousel'

  target 'WalkmoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
